create table belong(
    belong_id integer auto_increment,
    PRIMARY KEY (belong_id),
    relation_order_00 integer,
    FOREIGN KEY (relation_order_00) REFERENCES relation (relation_id),
    relation_order_01 integer,
    FOREIGN KEY (relation_order_01) REFERENCES relation (relation_id),
    relation_order_02 integer,
    FOREIGN KEY (relation_order_02) REFERENCES relation (relation_id),
    relation_order_03 integer,
    FOREIGN KEY (relation_order_03) REFERENCES relation (relation_id),
    relation_order_04 integer,
    FOREIGN KEY (relation_order_04) REFERENCES relation (relation_id),
    relation_order_05 integer,
    FOREIGN KEY (relation_order_05) REFERENCES relation (relation_id),
    relation_order_06 integer,
    FOREIGN KEY (relation_order_06) REFERENCES relation (relation_id),
    relation_order_07 integer,
    FOREIGN KEY (relation_order_07) REFERENCES relation (relation_id),
    relation_order_08 integer,
    FOREIGN KEY (relation_order_08) REFERENCES relation (relation_id),
    relation_order_09 integer,
    FOREIGN KEY (relation_order_09) REFERENCES relation (relation_id),
    relation_order_10 integer,
    FOREIGN KEY (relation_order_10) REFERENCES relation (relation_id),
    relation_order_11 integer,
    FOREIGN KEY (relation_order_11) REFERENCES relation (relation_id),
    relation_order_12 integer,
    FOREIGN KEY (relation_order_12) REFERENCES relation (relation_id),
    relation_order_13 integer,
    FOREIGN KEY (relation_order_13) REFERENCES relation (relation_id),
    relation_order_14 integer,
    FOREIGN KEY (relation_order_14) REFERENCES relation (relation_id),
    relation_order_15 integer,
    FOREIGN KEY (relation_order_15) REFERENCES relation (relation_id),
    relation_order_16 integer,
    FOREIGN KEY (relation_order_16) REFERENCES relation (relation_id),
    relation_order_17 integer,
    FOREIGN KEY (relation_order_17) REFERENCES relation (relation_id),
    relation_order_18 integer,
    FOREIGN KEY (relation_order_18) REFERENCES relation (relation_id),
    relation_order_19 integer,
    FOREIGN KEY (relation_order_19) REFERENCES relation (relation_id),
    relation_order_20 integer,
    FOREIGN KEY (relation_order_20) REFERENCES relation (relation_id)
);
